packages:
  - 'packages/*'
  - 'bench/*'
  - 'crates/*/js'
  - 'examples/next-app-router-4001'
  - 'turbopack/crates/*/js'
  - 'turbopack/crates/turbopack-tests/tests/execution'
  - 'turbopack/packages/*'
  - '../universe/packages/*'
  - '../universe/packages/bridge/*'
  - '../universe/packages/runtime-plugins/*'
